# Мой config.ini
[Settings window]
width = 1024
height = 768
resizable = False
title = Snake Game

# Примечание: задержка вызова функции движения змеи (Используется как сложность игры)
[Gameplay settings]
delay = 200 
snake_color_default = yellow
food_color_default = green

[Game place settings]
space_size = 32

