# Мой config.ini
[Settings window]
width = 1024
height = 768
resizable = False
title = Snake Game

# Примечание: задержка вызова функции движения змеи ипользуется как сложность игры
[Gameplay settings]
delay = 200 
snake_color = lime
food_color = red

[Game place settings]
space_size = 32

