# Мой config.ini
[Settings window]
width = 1024
height = 768
resizable = False
title = Snake Game

# Примечание: задержка вызова функции движения змеи ипользуется как сложность игры
[Gameplay settings]
delay = 200 
snake_color = violet
food_color = pink

[Game place settings]
space_size = 32
width_game_place = 640
height_game_place = 640
color_field_game_place = pink

[Other]
snake_facts = 🐍 Змеи не имеют век и спят с открытыми глазами!;🐍 Самая длинная змея в мире - сетчатый питон (до 10 метров);🐍 Змеи чувствуют запахи языком, а не носом!;🐍 В мире существует около 3000 видов змей;🐍 Змеи могут есть только раз в несколько месяцев;🐍 Самая быстрая змея - черная мамба (до 20 км/ч);🐍 Змеи глухие, но чувствуют вибрацию земли;🐍 Кобра может плеваться ядом на расстояние до 3 метров
