name: Auto test and deploy
on: push

jobs:
  test:
    name: Run tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Testing ...
        run: |
          cd game &&
          python main.py
